### ISSUE TITLE
[Golang 1.8] Cannot use grpc.Server

### ISSUE THREAD

**Issue by BenHall** [tedsuo/ot-walkthrough-go#3]
When attempting to run `./scripts/run_kitchen.sh -config config_example.yml` I get the following error:

```
dronutz/cmd/kitchen/kitchen.go:30: cannot use server (type *"google.golang.org/grpc".Server) as type *"
github.com/tedsuo/ot-walkthrough-go/vendor/google.golang.org/grpc".Server in argument to dronutz.RegisterKitchenServer
```

Environment has Golang 1.8 installed.

**Comment by tedsuo** [comment]
Hi Ben, thanks for the report. I'm not able to recreate this on go 1.8 or 1.7, and I've seen it compile many times. Can you confirm that none of your files have been edited?

**Comment by BenHall** [comment]
Strange. It must be my Golang config, I was using www.katacoda.com/courses/golang/playground environment

**Comment by tedsuo** [comment]
It looks like it's not understanding the `vendor` path correctly.

**Comment by BenHall** [comment]
Ahh. If I run it from `/gopath/src/github.com/tedsuo/ot-walkthrough-go` then everything appears to work as expected.

Thanks for your help.
